# -*- coding: utf-8 -*-
"""car_mileage_linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtLC0JQWlXda0lsjUiKOQMLilOtKaY6h

# Car Mileage Prediction using Linear Regression📏
# This project predicts car mileage (mpg) based on engine size, weight, and horsepower using linear regression

### importing modules
#### we import the nedded python modules to clean the data visuvalize the data and to use the ml model
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

"""###loading the data set using pandas🔃"""

data=pd.read_csv('/content/auto-mpg.csv')

"""####analyzing the dataset:👀"""

data

data.info()

"""###it describe the data like min max count only works on numerical rows"""

data.describe()

"""is null used to find the null values and .sum is used to sum those over here

"""

data.isnull().sum()

"""can't convert any numeric values in string when it contains any specialcharacters so it gives an error"""

data['horsepower'].isnull().sum()

"""##converting horsepower column into numeric type"""

data['horsepower']=pd.to_numeric(data['horsepower'],errors='coerce')

"""after converting to numeric we can find that we have 6 null values

"""

data['horsepower'].isnull().sum()

"""now replacing the null values with medaiin of horespower column and we use inplace true over here to modify in existing rows rather than creating a new one

"""

data['horsepower'].fillna(data['horsepower'].median(),inplace=True)

data['horsepower']

"""over here we have two many unneccsary columns so we have to drop those these dont affetct the mileage of the car so even if we drop them dont effect the out"""

data

"""so here we are dropping the colummns which are not needded"""

data.drop(['car name','origin','cylinders','acceleration','model year'],axis=1,inplace=True)

"""after dropping the columns we can see the new dataframe which are required for our machine learning model"""

data

"""#Training the Model
###we train the model using engine size,weight,horsepower and we wanna get the mileage as output
"""

x=data.drop(['mpg'],axis=1)
y=data['mpg']

"""we are splitting the data into two parts 80% training and 20% testing"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

"""asigning the data to our model"""

model=LinearRegression()
model.fit(x_train,y_train)

"""##now checking the predictions"""

predictions=model.predict(x_test)

print(predictions)

y_test

mse=mean_squared_error(predictions,y_test)
print(mse)

r2=r2_score(predictions,y_test)
print(r2)

mae = mean_absolute_error(y_test, predictions)

print(mae)

"""## Visualization: Weight vs Mileage,Weigt vs Displacement,Weight vs Horsepower

##scatter plot between Displacement and mileage
"""

x=data['displacement']
y=data['mpg']
plt.xlabel('displacement')
plt.ylabel('mileage')
plt.scatter(x,y)
plt.show()

"""##scatter plot between weight and mileage

"""

x=data['weight']
y=data['mpg']
plt.xlabel('weight')
plt.ylabel('mileage')
plt.scatter(x,y)
plt.show()

"""##scatter plot between horsepower and mileage"""

x=data['horsepower']
y=data['mpg']
plt.xlabel('horsepower')
plt.ylabel('mileage')
plt.scatter(x,y)
plt.show()

plt.scatter(data['weight'], data['mpg'], color='red', label='Weight')
plt.scatter(data['horsepower'], data['mpg'], color='green', label='Horsepower')
plt.scatter(data['displacement'], data['mpg'], color='blue', label='Displacement')

plt.xlabel('Feature Value')
plt.ylabel('Mileage (mpg)')
plt.legend()
plt.show()

