# -*- coding: utf-8 -*-
"""knn_in_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6cmArRILfF4j94YGJGgGcuXsHHG7Im-
"""

from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import neighbors,metrics

df=pd.read_csv('/content/car.data')

print(df.head(5))

x=df[['buying','maint','saftey']]
y=df[['class']]

label={
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}
y['class']=y['class'].map(label)

label1={
    'buying':{'vhigh':3, 'high':2,'med':1,'low':1},
    'maint':{'vhigh':3,'high':2,'med':1,'low':1},
    'saftey':{'high':3,'med':2,'low':1}
}

x=x.replace(label1).astype(int)
X=np.array(x)

print(X)

print(y)

Y=np.array(y)

print(Y)

"""
# creating model"""

knn=neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)
knn.fit(x_train,y_train)

prediction=knn.predict(x_test)

print("prediction:",prediction)

accuracy=metrics.accuracy_score(y_test,prediction)

print(accuracy)

print("actual value:",Y[200])
print("predicted value",knn.predict(X)[200])

