# -*- coding: utf-8 -*-
"""loan credit risk predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZAJWvHE-YMZavRXCuiWMi5Jf1H9CYes
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('/content/application_train.csv.zip')
df.shape

pd.set_option('display.max_columns',None)

df.head(5)

df['TARGET'].isnull().sum()

dropped=df.drop(columns=['SK_ID_CURR'],inplace=True)

df.columns

df.info()

df.describe()

df.isnull().sum()

df.isnull().sum().sum()

import seaborn as sn

plt.figure(figsize=(20,10))
sn.heatmap(df.isnull(),yticklabels=False,cbar=False,cmap='viridis')

(df.isnull().sum() / len(df)) * 100

per=(df.isnull().sum()/len(df))*100

print(per)

df_cleaned = df.drop(columns=per[per> 50].index)

print("Remaining columns:", df_cleaned.shape[1])

df.select_dtypes(include='object').columns.value_counts()

for i in df.columns:
  if df[i].dtype=='object':
    df[i]=pd.factorize(df[i])[0]

df.info()

df.isnull().sum().sum()

for i in df:
  df[i].fillna(df[i].mean(),inplace=True)

df.isnull().sum().sum()

sn.heatmap(df.isnull(),yticklabels=False,cbar=False,cmap='viridis')

df.head(20)

df.columns.size

x=df.drop('TARGET',axis=1)
y=df['TARGET']

from sklearn.model_selection import train_test_split as split

x_train,x_test,y_train,y_test=split(x,y,test_size=0.2,random_state=99)

from sklearn.tree import DecisionTreeClassifier as dt

model = dt(
    max_depth=5,
    class_weight='balanced',
    random_state=99
)

model.fit(x_train,y_train)

predictions=model.predict(x_test)

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

accuracy=accuracy_score(y_test,predictions)

print(accuracy)

confusion=confusion_matrix(y_test,predictions)

print(confusion)

classification=classification_report(y_test,predictions)

print(classification)

from sklearn.tree import plot_tree

plt.figure(figsize=(20,10))

plot_tree(
    model,
    feature_names=x.columns,
    class_names=True,
    filled=True
)

plt.show()

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(x_train, y_train)

predictions1= rf.predict(x_test)

accuracy1=accuracy_score(y_test,predictions)

print(accuracy1)

