# -*- coding: utf-8 -*-
"""svm_in_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ge-ordgAjPoMCZJL3hetBVjwvtsmGMTq
"""

from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

iris=datasets.load_iris()

x=iris.data
y=iris.target

print(x,y)

print(f"{x.shape},{y.shape}")

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

classes=['Iris Setosa','Iris Setosa','Iris Virginica']

model=svm.SVC()

model.fit(x_train,y_train)
print(model)

prediction=model.predict(x_test)
prediction

acc=accuracy_score(y_test,prediction)

print("prediction:",prediction)
print("actual:",y_test)
print("accuracy:",acc)

